### ISSUE TITLE
Joining values fail with the latest version

### ISSUE THREAD

**Issue by villesau** [harttle/liquidjs#212] opened 2020-03-30 15:10 UTC
Hi! 

Thanks for the great work with the library!

There seems to be a bug with joining values in the latest version.

Following code:

```
const l = require('liquidjs');
const engine = new l.Liquid();
const result = engine.parseAndRenderSync(
  `value-{{ value | split: " " | join \', value-\'}}`,
  { value: '123 321 123' }
);
console.log(result);

```

should produce output `value-123, value-321, value-123` , but instead it produces `value-123 321 123`

working version: 9.6.0
failing version: 9.11.7

**Comment by harttle** [comment] 2020-03-30 17:32
You missed `:` after `join`, should be written as:

```liquid
value-{{ value | split: " " | join \', value-\'}}
```

Sadly it's a regression but since the feature (I mean allowing omit the comma) is not intended and undocumented it's not marked as BREAKING CHANGES. Also see #208.

**Closed by harttle** 2020-03-30 17:32 UTC

**Comment by villesau** [comment] 2020-03-30 17:49
Thank you @harttle. Would it be possible to throw on invalid syntax? Or at least to have a flag for it? It's a bit problematic form usability perspective if it just fails silently.

**Comment by harttle** [comment] 2020-03-31 16:08
You're right. An error will be thrown in 9.11.8 and I listed it as a difference with shopify/liquid [here](https://liquidjs.com/tutorials/differences.html).

**Comment by villesau** [comment] 2020-03-31 16:52
@harttle great to hear! And really good job on maintaining the library, very much appreciated!
