### ISSUE TITLE
Unable to reassign include arguments locally within the include file itself

### ISSUE THREAD

**Issue by AleksandrHovhannisyan** [harttle/liquidjs#404] opened 2021-10-09 21:46 UTC
Related 11ty issue: https://github.com/11ty/eleventy/issues/2000

Steps to reproduce:

1. Create an include that accepts one argument.
2. Reassign the argument locally within the include.
3. Render the argument.
4. Invoke the include and specify a value for the argument.
5. Observe that the value does not get overridden.

Example:

**parent.html**

```liquid
{% include child.html color: "red" %}
```

**child.html**

```liquid
{% assign color = "green" %}{{ color }}
```

Expected behavior: the output is `green`.

Observed behavior: the output is `red`.

If it's okay, I'd like to take a crack at fixing this (if you think it's realistic for a first-time contributor). I have a failing test locally to confirm, but I'll need to figure out where in the code it's breaking.

**Comment by harttle** [comment] 2021-10-10 12:18
I see the current implementation is

```javascript
  render: function * (ctx: Context) {
    ctx.bottom()[this.key] = yield this.liquid._evalValue(this.value, ctx)
  }
```

It's assigning to the first scope in context stack. The idea is to skip transient scopes like the one created by `for`. Maybe we need mark which scope is a page-level one, and find the topmost page-level scope instead of `scopes[0]`. And I think the scope created by `include`, `render`, `layout` should be considered page-level.

Feel free to post back if you're stuck. I can help or continue your work!

**Comment by AleksandrHovhannisyan** [comment] 2021-10-30 13:23
Hi @harttle, thanks for getting back and clarifying! Unfortunately, I don't think I'll be able to tackle this ticket. Please feel free to assign it to someone else or continue where I left off.

(As an aside: I think it may be worth documenting some of the code, with inline comments or jsDoc, to make it easier for others to contribute. This was my biggest pain point.)

**Comment by harttle** [comment] 2021-10-30 15:40
@AleksandrHovhannisyan feel free to create a pull request (even incomplete), I can try to continue your work. At least I also think it's a bug worth fixing.

**Comment by harttle** [comment] 2021-10-31 08:45
After digging into Liquid and LiquidJS (I wrote this part long time ago and it takes me quite a while to figure it out, sorry for this), I find that:

`include` and `layout` are legacy tags which does not provide Context separation. In both Shopify/Liquid and LiquidJS, `{% assgin %}` in `{%include%}` files assigns to its parent template, thus will not hide include arguments. So it's by design and that's why `{%include%}` tag is deprecated.

`render` enforces Context separation by creating a new `Context` when render partials, but it has a bug resulting in `{% assign %}` inside `{%render%}` also not hiding render arguments. It's definitely a bug and not consistent with Shopify/Liquid, I updated @AleksandrHovhannisyan 's PR and fixed this bug on v9.28.4, check it out!

`layout` is implemented just like `include` and still not works for now, I'll consider provide a substitution for `layout` too if someone actually needs that.

**Comment by AleksandrHovhannisyan** [comment] 2021-10-31 11:35
@harttle Sounds good, thank you!

Since 11ty uses `include` and not `render`, does this mean that the bug won't be fixed for us unless we upgrade to the latest version? I'm specifically wondering about this test:

https://github.com/harttle/liquidjs/commit/124f4c4485270a5fdfca610808a56ecd98d98417#diff-d31563acb42db2c893c52aa0555c10ce781e05097b0b59cd5a403472972e7300R91

**Comment by pdehaan** [comment] 2021-10-31 17:16
@AleksandrHovhannisyan I'm pretty sure 11ty v1 (beta) supports the `render` tag as well (although it's been a while since I've played with that).

Although I do see that https://github.com/11ty/eleventy/blob/19b4884e83e420a3b42f334aa922140f9cb18353/package.json#L107 is pinned to a very specific version of liquidjs, so we might need to tweak that line from the 11ty side (or else you can try manually installing the latest liquidjs locally and then try [setting your own custom library instance](https://www.11ty.dev/docs/languages/liquid/#optional-set-your-own-library-instance).

**Comment by AleksandrHovhannisyan** [comment] 2021-10-31 17:24
@pdehaan Gotcha—yeah, [Zach mentioned](https://github.com/11ty/eleventy/issues/2000#issuecomment-945194370) that even if this fix got in, we wouldn't be able to take advantage of it yet due to this regression, which is pinning liquid to `9.25.x`: https://github.com/11ty/eleventy/issues/1995.

**Closed** 2021-12-07 14:45 UTC
Labels: bug
