### ISSUE TITLE
Better caching support

### ISSUE THREAD

**Issue by ankopainting** [harttle/liquidjs#196] opened 2020-02-27 23:04 UTC
Thanks for an excellent project.

We have a long running nodejs application which is parsing templates that can be up to 3MB.  As you can imagine, the parsing/tokenising stages can take a while.  We can turn cache: true on in the options, but eventually it eats all our memory. 

We also tried to do a parse call which gives us an ITemplate[], which we cache ourselves until we need to render it.  This works quite well, but we are still consuming a LOT of memory.  A 40KB template is using about 1.2MB in our cache.

So I guess there are two requests here;

1) could we have a max entries in the cache? So it evicts the oldest? like an LRU cache?
2) Is there a way we could serialise the parsed/tokenised template to json or something, ie. no complex objects

**Comment by harttle** [comment] 2020-02-28 03:03
> A 40KB template is using about 1.2MB in our cache.

It's a problem need to be addressed. I suppose in the end it can be optimized to 50KB - 70KB or so, it can't be less than 40KB AFAIK.

1. I can extract cache storage (aka. get and set) as a separated object (implement as LRU is good by default) which can be substituted.
2. Templates didn't implement a serialize method currently, but it's sounds good to do so.

**Comment by ankopainting** [comment] 2020-03-02 00:44
This is great, thanks for listening to my problems :)

**Comment by harttle** [comment] 2020-03-03 23:17
Try 9.10.0, the [cache option](https://harttle.land/liquidjs/interfaces/_liquid_options_.liquidoptions.html#cache) now supports a number of LRU limit, or a custom cache object which implements `read()`, `write()`, `has()`.  Test cases for `cache=2` and `cache=Object`:

https://github.com/harttle/liquidjs/blob/607a5cda3f049cc2cec17f77f9ba29706e8e46bf/test/integration/liquid/cache.ts#L47-L84

**Comment by ankopainting** [comment] 2020-03-04 02:08
I am working on a different problem right now, but if you can bare with me for a week I can get it into the next sprint :) thank you so much for this! 

The only thing i can think of (on my earliest thought) is that if the cache is remotely stored, having a "has" and a separate "read" function will require 2 round trips to the server.  But for my purposes i suppose i could work around it issuing a redis GET for the "has" and storing the value locally - the read() should be called soon after.  I'll just have to fall back 2 two round trips if there are highly concurrent accesses.

**Comment by harttle** [comment] 2020-03-04 18:31
You're right, an additional `has()` method is useless and I've removed it in 61dac49b042390f8e126453ef318c2371d62d213 and added async support for both `read()` and `write()` since @9.11.0.

But I find it non-trivial to implement serialize/unserialize for the template since it depends on the exact implementation details in each tag. We're running into a similar situation as #93. Instead of patching every tag, maybe it's better to maintain a dedicated plugin with a fixed version of tags , as suggested in https://github.com/harttle/liquidjs/issues/93#issuecomment-471280370.

And I didn't reproduce the above mentioned memory problem, I'll close this issue and if a detailed template set and Node.js version can be provided, feel free to file another issue.

**Closed by harttle** 2020-03-04 18:31 UTC
Labels: feature requested, performance
